### ISSUE TITLE
Question on Brueckner

### ISSUE THREAD

**Issue by vvp-nsk** [BoothGroup/ebcc#51]
Hej!

I am sorry to bother you again but would like to clarify one issue. If one combines Brueckner orbital rotation with the DCSD ansatz, would it effectively result in the so-called [BDCD](https://pubs.aip.org/aip/jcp/article/141/6/061101/353351/Communication-The-distinguishable-cluster) approach? 

Thank you in advance!

With best regards, 
Victor

**Comment by obackhouse** [comment]
Not a bother -- yes, that is correct. I believe that I have compared BDCD against literature values when I was adding DCD and DCSD, though I didn't write a unit test for this. Let me know if you try it and the results don't seem to match expectation.
